[1/5] cd /Users/wcravens/Repos/pididah/sandbox/key_gpio_debounce/build/esp-idf/esptool_py && /Users/wcravens/.espressif/python_env/idf5.0_py3.11_env/bin/python /Users/wcravens/Repos/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 partition --type app /Users/wcravens/Repos/pididah/sandbox/key_gpio_debounce/build/partition_table/partition-table.bin /Users/wcravens/Repos/pididah/sandbox/key_gpio_debounce/build/key_gpio_debounce.bin
key_gpio_debounce.bin binary size 0x331b0 bytes. Smallest app partition is 0x100000 bytes. 0xcce50 bytes (80%) free.
[2/5] Performing build step for 'bootloader'
[1/1] cd /Users/wcravens/Repos/pididah/sandbox/key_gpio_debounce/build/bootloader/esp-idf/esptool_py && /Users/wcravens/.espressif/python_env/idf5.0_py3.11_env/bin/python /Users/wcravens/Repos/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x0 /Users/wcravens/Repos/pididah/sandbox/key_gpio_debounce/build/bootloader/bootloader.bin
Bootloader binary size 0x5180 bytes. 0x2e80 bytes (36%) free.
[3/5] No install step for 'bootloader'
[4/5] Completed 'bootloader'
[4/5] cd /Users/wcravens/Repos/esp/esp-idf/components/esptool_py && /usr/local/Cellar/cmake/3.25.2/bin/cmake -D IDF_PATH=/Users/wcravens/Repos/esp/esp-idf -D "SERIAL_TOOL=/Users/wcravens/.espressif/python_env/idf5.0_py3.11_env/bin/python;;/Users/wcravens/Repos/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3" -D "SERIAL_TOOL_ARGS=--before=default_reset;--after=hard_reset;write_flash;@flash_args" -D WORKING_DIRECTORY=/Users/wcravens/Repos/pididah/sandbox/key_gpio_debounce/build -P /Users/wcravens/Repos/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
esptool esp32s3 -p /dev/cu.SLAB_USBtoUART -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 80m --flash_size 2MB 0x0 bootloader/bootloader.bin 0x10000 key_gpio_debounce.bin 0x8000 partition_table/partition-table.bin
esptool.py v4.5.1
Serial port /dev/cu.SLAB_USBtoUART
Connecting...

A serial exception error occurred: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
Note: This error originates from pySerial. It is likely not a problem with esptool, but with the hardware connection or drivers.
For troubleshooting steps visit: https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html
FAILED: CMakeFiles/flash /Users/wcravens/Repos/pididah/sandbox/key_gpio_debounce/build/CMakeFiles/flash 
cd /Users/wcravens/Repos/esp/esp-idf/components/esptool_py && /usr/local/Cellar/cmake/3.25.2/bin/cmake -D IDF_PATH=/Users/wcravens/Repos/esp/esp-idf -D "SERIAL_TOOL=/Users/wcravens/.espressif/python_env/idf5.0_py3.11_env/bin/python;;/Users/wcravens/Repos/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3" -D "SERIAL_TOOL_ARGS=--before=default_reset;--after=hard_reset;write_flash;@flash_args" -D WORKING_DIRECTORY=/Users/wcravens/Repos/pididah/sandbox/key_gpio_debounce/build -P /Users/wcravens/Repos/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
ninja: build stopped: subcommand failed.
